version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "autostart_codesel-network"]
    ports:
      - "4444:4444"
    networks:
      - codesel-network
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - codesel-network
networks:
  codesel-network:
    driver: bridge
